apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:                                    #pod Label and Service Selector should be same 
    env: prod
    app: webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort